services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    KimaiPlugin\MileageExpenseBundle\:
        resource: '../../*'
        exclude:
            - '../../Resources'
            - '../../Migrations'
